name: "Build & Release"

on:
  push:
    branches:
      - main
  workflow_dispatch:
    
jobs:
    build-windows:
        name: Build Windows
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup-Java
              uses: actions/setup-java@v3.12.0
              with:
                distribution: 'oracle'
                java-version: '17'

            - name: Create debug keystore
              run: |
                keytool -genkey -v -keystore android/app/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.35.4'
                channel: 'stable'

            - name: Install Dependencies
              run: flutter pub get

            - name: Extract version from pubspec.yaml
              shell: powershell
              run: |
                  $vLine = Select-String -Path pubspec.yaml -Pattern '^version:\s*(\S+)' | Select-Object -First 1
                  if (-not $vLine) { Write-Error 'version not found in pubspec.yaml'; exit 1 }
                  $ver = $vLine.Matches[0].Groups[1].Value.Split('+')[0]
                  echo "VERSION=$ver" >> $env:GITHUB_ENV

            - name: Build Windows App
              run: flutter build windows --release --build-number ${{github.run_number}}
            
            - name: Rename file
              run: Rename-Item -Path "build/windows/x64/runner/Release/BeatWave.exe" -NewName "BeatWave.exe"
           
            - name: ZIP build
              run: Compress-Archive -Path build/windows/x64/runner/Release/* -Destination  build/windows/x64/beatwave_windows_x64_v${{ env.VERSION }}+${{github.run_number}}.zip
            
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Release-Windows
                path: build/windows/x64/beatwave_windows_x64_v${{ env.VERSION }}+${{github.run_number}}.zip
